version: '3.8'

services:

  db:
    environment:
        - MYSQL_DATABASE=SimpleCrud
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
    image: mysql:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - spring-mysql
    ports:
    - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db" ]
      timeout: 20s
      retries: 10

  crud:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: crud-app
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SimpleCrud?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      server.address: 0.0.0.0
    networks:
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy

networks:
  spring-mysql:
    name: spring-mysql
    driver: bridge

volumes:
  db_data: {}
